# Generated by Django 6.0 on 2026-01-08 09:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gameweek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fpl_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=20)),
                ('deadline_time', models.DateTimeField()),
                ('finished', models.BooleanField()),
                ('is_current', models.BooleanField()),
                ('is_next', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fpl_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=20)),
                ('short_name', models.CharField(max_length=5)),
                ('squad_select', models.IntegerField()),
                ('squad_min_play', models.IntegerField(null=True)),
                ('squad_max_play', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fpl_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=5)),
                ('strength', models.IntegerField()),
                ('strength_overall_home', models.IntegerField()),
                ('strength_overall_away', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('fpl_team_id', models.IntegerField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fpl_id', models.IntegerField(unique=True)),
                ('web_name', models.CharField(max_length=50)),
                ('player_code', models.CharField(max_length=20, null=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('second_name', models.CharField(max_length=50, null=True)),
                ('now_cost', models.IntegerField()),
                ('total_points', models.IntegerField()),
                ('status', models.CharField(max_length=1)),
                ('minutes', models.IntegerField(default=0)),
                ('goals_scored', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('clean_sheets', models.IntegerField(default=0)),
                ('goals_conceded', models.IntegerField(default=0)),
                ('saves', models.IntegerField(default=0)),
                ('bonus', models.IntegerField(default=0)),
                ('bps', models.IntegerField(default=0)),
                ('yellow_cards', models.IntegerField(default=0)),
                ('red_cards', models.IntegerField(default=0)),
                ('own_goals', models.IntegerField(default=0)),
                ('penalties_missed', models.IntegerField(default=0)),
                ('penalties_saved', models.IntegerField(default=0)),
                ('influence', models.FloatField(default=0)),
                ('creativity', models.FloatField(default=0)),
                ('threat', models.FloatField(default=0)),
                ('defensive_contribution', models.IntegerField(default=0)),
                ('expected_goals', models.FloatField(default=0)),
                ('expected_assists', models.FloatField(default=0)),
                ('expected_goal_involvements', models.FloatField(default=0)),
                ('expected_goals_conceded', models.FloatField(default=0)),
                ('form', models.FloatField(default=0)),
                ('points_per_game', models.FloatField(default=0)),
                ('chance_of_playing_this_round', models.IntegerField(null=True)),
                ('chance_of_playing_next_round', models.IntegerField(null=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.position')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.team')),
            ],
        ),
    ]
